import sqlite3

def execute_sql_on_warehouse(sql_query: str) -> list[dict]:
    """
    Connects to the SQLite Data Warehouse, executes the safe query,
    and returns the results as a clean list of dictionaries.
    """
    # Connect to our dummy external data warehouse
    conn = sqlite3.connect("data_warehouse.db")
    
    # This is a crucial setting: It forces SQLite to return rows as dictionaries 
    # (e.g., {"region": "south", "revenue": 500}) instead of plain tuples (e.g., ("south", 500))
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    try:
        # We only execute standard SELECT queries generated by our deterministic builder
        cursor.execute(sql_query)
        rows = cursor.fetchall()
        
        # Convert the sqlite3.Row objects to standard Python dictionaries for JSON serialization
        return [dict(row) for row in rows]
    
    except Exception as e:
        raise ValueError(f"Data Warehouse Execution Error: {str(e)}")
    
    finally:
        conn.close()